# -*- coding: utf-8 -*-
"""HW2_Simner_Sidney.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tECwI7NvGoOEh0--9WzNYkUxEsCcpMEw

## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.

**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.
"""

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 3]}

# Type your solution here
import numpy as np
import pandas as pd

#create dataframe
df = pd.DataFrame(data)
print(df)

#Q1-2
psych = df[(df['job'] == 'psychologist') & (df['num_cars'] > df['family_size'])]
teacher = df[(df['job'] == 'teacher') & (df['num_cars'] > df['family_size'])]

#add the results to a new dataframe
df1 = pd.DataFrame(psych)
df2 = pd.DataFrame(teacher)

#combine results
result = pd.concat([df1, df2])

print(result)

#Q1-3
df[(df['family_size'] <= 2) & (df['num_cars'] > 0)]

#Q1-4
df['job'].unique()

"""**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**"""

import numpy as np
import pandas as pd

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

#create dataframe of the fruits and their weights
data = {'fruits' : fruit, 'weights' : weights}
df = pd.DataFrame(data)
print(df)
print()

#create new dataframs for each fruit
apples = df[(df.fruits == "apple")]
bananas = df[(df.fruits == "banana")]
carrots = df[(df.fruits == "carrot")]

#make arrays of each fruits weights
a_array = apples["weights"].values
b_array = bananas["weights"].values
c_array = carrots["weights"].values

#initialize variables
applesums = 0
bananasum = 0 
carrotsums = 0

#sum the fruit weights
for a in a_array:
  applesums += a
for b in b_array:
  bananasum += b
for c in c_array:
  carrotsums += c

print("Average apple weight:", applesums/len(a_array))
print("Average banana weight:", bananasum/len(b_array))
print("Average carrot weight:", carrotsums/len(c_array))

"""**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".

"""

import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
print(course_name)

#Q3-1
#create a dictionary with the array paired with its index 
courseDict = {}

for i in range(5):
  courseDict[course_name[i]] = i

print(courseDict)

#sort the array by making it into a list 
courselist = course_name.tolist()
sortlist = sorted(courselist)
print(sortlist)

#make a list of the indexes of the sorted elements
indexes = []
for x in sortlist:
  indexes.append(courseDict[x])

print(indexes)
print()

#Q3-2
for e in courselist:
  if e[0].lower() == 'p':
    print(e, "starts with a P!")
  else:
    print(e, "does not start with a P")

"""**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.
"""

import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# Q4-1
print(student_id)
flipped = np.flip(student_id)
print(flipped)

#Q4-2
student_id.sort()
print(student_id[-3:])

"""**Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**"""

# Type your solution here -- use a funciton 
nums = np.arange(3,100,1)

#initialize variable
sum = 0

#traverse all the possible numbers
for x in nums:
  if x % 3 == 0 or x % 5 == 0:
    sum += x

print(sum)

"""**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.
"""

import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

#swap first two columns
arr[:, [0, 1]] = arr[:, [1, 0]] 

print(arr)

#reset to origional array
arr = np.arange(12).reshape(3,4)

#swap first two rows
arr[[0, 1], :] = arr[[1, 0], :] 
print(arr)